{{- if .Values.imageCredentials.enabled }}
# ⚠️ 明文凭证进 Git，仅限 dev 临时验证；生产走 sealedSecrets（ADR-8）
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "generic-service.fullname" . }}-registry
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "generic-service.imagePullSecret" . }}
{{- end }}
